### ISSUE TITLE
Image 'cron:latest' missing

### ISSUE THREAD

**Issue by davidearlotto** [Alexis-benoist/docker-cron-example#1]
Hi Alexis, 
when I try to run it locally, it retrieves me the following error:

`Unable to find image 'cron:latest' locally \
Pulling repository docker.io/library/cron \
docker: Error: image library/cron not found.`

How can I prevent this?

Thanks

**Comment by aglynnej** [comment]
I just hit this issue too.
To get it to work the docker run command should use cron-example not just cron to match the example build command, like this:
docker run -v /path/to/cron_docker/logs:/var/log cron-example

I suggest Alexis changes the readme file to correct this typo.
